title: DS Portfolio
logo /https://btgroupcloud-my.sharepoint.com/:i:/r/personal/david_elliott_ee_co_uk/Documents/Pictures/EE_logo.png?e=4%3acad765be8dca4f02a81a1bdbcc433fb0&web=1&sharingv2=true&fromShare=true&at=9&xsdata=MDV8MDJ8ZGF2aWQuZWxsaW90dEBlZS5jby51a3xkZGVjOTk4ZmQ0NjY0ODdlNzM1ZTA4ZGU0OTUxZWE1ZnxhN2YzNTY4ODljMDA0ZDVlYmE0MTI5ZjE0NjM3N2FiMHwwfDB8NjM5MDI4ODEzMzI0NTg3NDE1fFVua25vd258VFdGcGJHWnNiM2Q4ZXlKRmJYQjBlVTFoY0draU9uUnlkV1VzSWxZaU9pSXdMakF1TURBd01DSXNJbEFpT2lKWGFXNHpNaUlzSWtGT0lqb2lUV0ZwYkNJc0lsZFVJam95ZlE9PXwwfHx8&sdata=ZmN6QnExQ1hoVStXQVpzWjc0YlJpMW01M25vRklLb2dPR3FIVVBmQTlNWT0%3d
#description: text below image
show_downloads: ture
theme:jekyll-theme-minimal
